// Copyright (c) 2026 Raman Dzehtsiar
// SPDX-License-Identifier: MIT

/*
 * libfuse_config.h - version macros for the AIX USFS libfuse reimplementation.
 *
 * In upstream libfuse this file is generated by the meson build; here it is a
 * plain header. The version mirrors the libfuse release whose API this
 * library reproduces (interface compatibility only).
 */

#ifndef LIBFUSE_CONFIG_H
#define LIBFUSE_CONFIG_H

#define FUSE_MAJOR_VERSION  3
#define FUSE_MINOR_VERSION  19
#define FUSE_HOTFIX_VERSION 0

#endif /* LIBFUSE_CONFIG_H */
