/*
 * Copyright (c) 2026 Raman Dzehtsiar
 * SPDX-License-Identifier: MIT
 */

#ifndef USFS_ERRIDS_H
#define USFS_ERRIDS_H

/*
 * Scanner fallback generated by AIX errupdate -h -n. AIX kernel builds put
 * the freshly generated header in out/generated ahead of this include path.
 */
#define ERRID_USFS_TIMEOUT        0x367cfadbu
#define ERRID_USFS_PROTOCOL       0x03cb297bu
#define ERRID_USFS_DAEMON_LOST    0x0b6dd74bu
#define ERRID_USFS_FORCE_RECOVERY 0xbdaf4d05u
#define ERRID_USFS_CLEANUP_REQ    0x5d669390u

#endif
